FROM python:3.11.6-slim
FROM node:20.11.0-alpine

WORKDIR /app
COPY . /app

RUN pip install poetry
RUN poetry install -C packages/scraper
RUN poetry install -C packages/api

RUN npm install
RUN npm run turbo run setup
RUN npm run turbo run scrape