[tool.poetry]
name = "gbbo-scraper"
version = "0.1.0"
description = "GBBO Recipe Scraper"
authors = ["Blake Netzeband <blake.netzeband@gmail.com>"]
readme = "../../README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
dateparser = "^1.2.0"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"

[tool.poetry.scripts]
init-db = "db-setup:main"
scrape = "main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
